import { useMutation } from "@tanstack/react-query";
import { CheckCircle2, FileKey2, ScanSearch } from "lucide-react";
import { useState } from "react";
import { useApi } from "../../shared/auth/SessionProvider";
import { JsonBlock } from "../../shared/components/JsonBlock";
import { PageHeader } from "../../shared/components/PageHeader";

export function WorkbenchPage() {
  const api = useApi(); const [artifact, setArtifact] = useState(""); const [projection, setProjection] = useState("");
  const verifyArtifact = useMutation({ mutationFn: () => api.verifyDecisionArtifact(artifact) });
  const verifyProjection = useMutation({ mutationFn: () => api.verifyProjection(projection) });
  return <><PageHeader eyebrow="Verification" title="Authority workbench" description="Validate signed evidence without retaining credential material." /><div className="workbench-grid"><section className="content-section workbench-panel"><div className="section-heading"><div className="workbench-title-icon"><FileKey2 size={19} /></div><div><span className="section-kicker">Decision evidence</span><h2>Verify artifact</h2></div></div><label className="field"><span>Signed decision artifact</span><textarea rows={7} value={artifact} onChange={(event) => setArtifact(event.target.value)} spellCheck="false" /></label><button className="button button-primary" disabled={!artifact.trim() || verifyArtifact.isPending} onClick={() => verifyArtifact.mutate()}><ScanSearch size={16} />Verify artifact</button>{verifyArtifact.error ? <p className="form-error">{verifyArtifact.error.message}</p> : null}{verifyArtifact.data ? <div className="verification-result"><div><CheckCircle2 size={18} /><strong>Verification complete</strong></div><JsonBlock value={verifyArtifact.data} label="Artifact result" /></div> : null}</section><section className="content-section workbench-panel"><div className="section-heading"><div className="workbench-title-icon workbench-title-violet"><FileKey2 size={19} /></div><div><span className="section-kicker">Gateway credential</span><h2>Verify projection</h2></div></div><label className="field"><span>Projection token</span><textarea rows={7} value={projection} onChange={(event) => setProjection(event.target.value)} spellCheck="false" /></label><button className="button button-primary" disabled={!projection.trim() || verifyProjection.isPending} onClick={() => verifyProjection.mutate()}><ScanSearch size={16} />Verify projection</button>{verifyProjection.error ? <p className="form-error">{verifyProjection.error.message}</p> : null}{verifyProjection.data ? <div className="verification-result"><div><CheckCircle2 size={18} /><strong>Verification complete</strong></div><JsonBlock value={verifyProjection.data} label="Projection result" /></div> : null}</section></div></>;
}
