/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOperationsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mission-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMissionProposals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mission-proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMissionProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExpansionRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tool-contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listToolContracts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContainmentRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiError: {
            error?: string;
            code: string;
            message: string;
        };
        Principal: {
            subject: string;
            issuer: string;
        };
        Agent: {
            provider: string;
            client_id: string;
            instance_id: string;
        };
        ResourceGrant: {
            type: string;
            id: string;
            actions: string[];
            constraints?: {
                [key: string]: unknown;
            };
        };
        AuthorityRegion: {
            resources: components["schemas"]["ResourceGrant"][];
            forbidden_actions?: string[];
        };
        Delegation: {
            [key: string]: unknown;
        };
        Lifecycle: {
            [key: string]: unknown;
        };
        Mission: {
            mission_id: string;
            mission_ref: string;
            tenant_id: string;
            state: string;
            version: number;
            principal: components["schemas"]["Principal"];
            agent: components["schemas"]["Agent"];
            purpose: {
                [key: string]: unknown;
            };
            authority_region: components["schemas"]["AuthorityRegion"];
            conditions?: {
                [key: string]: unknown;
            }[];
            lifecycle: components["schemas"]["Lifecycle"];
            delegation: components["schemas"]["Delegation"];
        };
        MissionProposal: {
            proposal_id: string;
            status: string;
            tenant_id: string;
            principal: components["schemas"]["Principal"];
            agent: components["schemas"]["Agent"];
            intent: {
                [key: string]: unknown;
            };
            authority_region: components["schemas"]["AuthorityRegion"];
            lifecycle: components["schemas"]["Lifecycle"];
            delegation: components["schemas"]["Delegation"];
            /** Format: date-time */
            created_at: string;
        };
        ExpansionRequest: {
            [key: string]: unknown;
        };
        AgentIdentity: {
            [key: string]: unknown;
        };
        ToolContract: {
            [key: string]: unknown;
        };
        Projection: {
            [key: string]: unknown;
        };
        EventRecord: {
            [key: string]: unknown;
        };
        ContainmentRule: {
            [key: string]: unknown;
        };
        AdminSession: {
            principal: components["schemas"]["Principal"];
            capabilities: {
                [key: string]: boolean;
            };
            api_version: string;
        };
        OperationsSummary: {
            missions_total: number;
            missions_by_state: {
                [key: string]: number;
            };
            pending_proposals: number;
            pending_expansions: number;
            active_containments: number;
            active_agents: number;
            active_projections: number;
            recent_event_count: number;
            service_capabilities: {
                [key: string]: unknown;
            };
        };
        MissionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Mission"][];
        };
        ProposalPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["MissionProposal"][];
        };
        ExpansionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["ExpansionRequest"][];
        };
        AgentPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["AgentIdentity"][];
        };
        ToolContractPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["ToolContract"][];
        };
        ProjectionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Projection"][];
        };
        EventPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["EventRecord"][];
        };
        Page: {
            items: unknown[];
            next_cursor?: string;
            total: number;
        };
    };
    responses: {
        /** @description Stable API error envelope. */
        Error: {
            headers: {
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        Tenant: string;
        Query: string;
        Status: string;
        State: string;
        Type: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated administrator context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOperationsSummary: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current operator dashboard counters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMissions: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMissionProposals: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission proposal page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMissionProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission proposal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionProposal"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExpansionRequests: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expansion request page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpansionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent identity page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listToolContracts: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool contract page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolContractPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjections: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projection page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit event page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getContainmentRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containment rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
