/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/mission-authority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMissionAuthorityDiscovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/authzen-configuration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthZENDiscovery"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access/v1/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["evaluateAuthZEN"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/access/v1/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["evaluateAuthZENBatch"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAdminSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/operations/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getOperationsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMissions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["evaluateMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/authority/negotiations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAuthorityNegotiation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/expansion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createExpansionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resumeMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/delegate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delegateMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["completeMission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/introspect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["introspectMission"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMissionLineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/missions/{mission_ref}/leases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createMissionLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mission-proposals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMissionProposals"];
        put?: never;
        post: operations["createMissionProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mission-proposals/{proposal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getMissionProposal"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/mission-proposals/{proposal_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveMissionProposal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listExpansionRequests"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests/{expansion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getExpansionRequest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests/{expansion_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["approveExpansionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests/{expansion_id}/deny": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["denyExpansionRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/expansion-requests/{expansion_id}/approvals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["submitExpansionApproval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["registerAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agent_id}/lineage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgentLineage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tool-contracts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listToolContracts"];
        put?: never;
        post: operations["registerToolContract"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tool-contracts/{tool_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getToolContract"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tool-calls/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["authorizeToolCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections/{projection_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getProjectionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections/{projection_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["revokeProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/projections/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/github/repositories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listGitHubRepositoryBindings"];
        put?: never;
        post: operations["createGitHubRepositoryBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/github/webhooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["ingestGitHubWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/github/check-runs/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["planGitHubCheckRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/okta/app-bindings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOktaAppBindings"];
        put?: never;
        post: operations["createOktaAppBinding"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/okta/authority-context/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveOktaAuthorityContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/entra/app-registrations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEntraAppRegistrations"];
        put?: never;
        post: operations["createEntraAppRegistration"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/integrations/entra/authority-context/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["resolveEntraAuthorityContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/approval-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApprovalRules"];
        put?: never;
        post: operations["createApprovalRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listContainmentRules"];
        put?: never;
        post: operations["createContainmentRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContainmentRule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment-rules/{rule_id}/lift": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["liftContainmentRule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/containment-rules/{rule_id}/blast-radius": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getContainmentBlastRadius"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/authority/negotiations/{negotiation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAuthorityNegotiation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/decision-artifacts/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["verifyDecisionArtifact"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/leases/{lease_id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["refreshMissionLease"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        GenericObject: {
            [key: string]: unknown;
        };
        ApiError: {
            error?: string;
            code: string;
            message: string;
        };
        Principal: {
            subject: string;
            issuer: string;
        };
        Agent: {
            provider: string;
            client_id: string;
            instance_id: string;
        };
        ResourceGrant: {
            type: string;
            id: string;
            actions: string[];
            constraints?: {
                [key: string]: unknown;
            };
        };
        AuthorityRegion: {
            resources: components["schemas"]["ResourceGrant"][];
            forbidden_actions?: string[];
        };
        Delegation: {
            [key: string]: unknown;
        };
        Lifecycle: {
            [key: string]: unknown;
        };
        Mission: {
            mission_id: string;
            mission_ref: string;
            tenant_id: string;
            state: string;
            version: number;
            principal: components["schemas"]["Principal"];
            agent: components["schemas"]["Agent"];
            purpose: {
                [key: string]: unknown;
            };
            authority_region: components["schemas"]["AuthorityRegion"];
            conditions?: {
                [key: string]: unknown;
            }[];
            lifecycle: components["schemas"]["Lifecycle"];
            delegation: components["schemas"]["Delegation"];
        };
        MissionProposal: {
            proposal_id: string;
            status: string;
            tenant_id: string;
            principal: components["schemas"]["Principal"];
            agent: components["schemas"]["Agent"];
            intent: {
                [key: string]: unknown;
            };
            authority_region: components["schemas"]["AuthorityRegion"];
            lifecycle: components["schemas"]["Lifecycle"];
            delegation: components["schemas"]["Delegation"];
            /** Format: date-time */
            created_at: string;
        };
        ExpansionRequest: {
            [key: string]: unknown;
        };
        AgentIdentity: {
            [key: string]: unknown;
        };
        ToolContract: {
            [key: string]: unknown;
        };
        Projection: {
            [key: string]: unknown;
        };
        EventRecord: {
            [key: string]: unknown;
        };
        ContainmentRule: {
            [key: string]: unknown;
        };
        CreateGitHubRepositoryBindingRequest: {
            tenant_id?: string;
            owner?: string;
            repo?: string;
            /** @description Repository in owner/repo form. */
            repository?: string;
            default_branch?: string;
            /** Format: int64 */
            installation_id?: number;
            mission_ref?: string;
            branch_patterns?: string[];
            required_checks?: string[];
            metadata?: {
                [key: string]: string;
            };
        };
        GitHubRepositoryBinding: {
            binding_id: string;
            tenant_id?: string;
            repository: string;
            mission_ref?: string;
            status: string;
            /** Format: date-time */
            created_at: string;
        } & {
            [key: string]: unknown;
        };
        GitHubWebhookResponse: {
            accepted: boolean;
            status: string;
            event: string;
            delivery_id: string;
            repository?: string;
            binding_id?: string;
            mission_ref?: string;
        } & {
            [key: string]: unknown;
        };
        GitHubChangedFile: {
            path: string;
            status?: string;
            operation?: string;
            additions?: number;
            deletions?: number;
        };
        GitHubCheckRunPlanRequest: {
            mission_ref?: string;
            mission_version_seen?: number;
            actor: {
                [key: string]: unknown;
            };
            repository: string;
            pull_request?: number;
            head_sha: string;
            branch?: string;
            changed_files: components["schemas"]["GitHubChangedFile"][];
            context?: {
                [key: string]: unknown;
            };
        };
        GitHubCheckRunPlanResponse: {
            name: string;
            external_id: string;
            repository: string;
            head_sha: string;
            status: string;
            conclusion: string;
            title: string;
            summary: string;
            mission_ref: string;
            mission_version?: number;
            evaluations: {
                [key: string]: unknown;
            }[];
        } & {
            [key: string]: unknown;
        };
        CreateOktaAppBindingRequest: {
            tenant_id?: string;
            /** @description Okta issuer, for example https://example.okta.com/oauth2/default. */
            issuer: string;
            authorization_server_id?: string;
            client_id: string;
            app_id?: string;
            app_label?: string;
            mission_ref: string;
            required_groups?: string[];
            admin_groups?: string[];
            allowed_subjects?: string[];
            group_claim?: string;
            subject_claim?: string;
            scope_claim?: string;
            /** @enum {string} */
            group_match_mode?: "any" | "all";
            metadata?: {
                [key: string]: string;
            };
        };
        OktaAppBinding: {
            binding_id: string;
            tenant_id?: string;
            issuer: string;
            authorization_server_id?: string;
            discovery_url?: string;
            jwks_uri?: string;
            client_id: string;
            app_id?: string;
            app_label?: string;
            mission_ref: string;
            required_groups?: string[];
            admin_groups?: string[];
            allowed_subjects?: string[];
            group_claim?: string;
            subject_claim?: string;
            scope_claim?: string;
            group_match_mode?: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_resolved_at?: string;
            last_subject?: string;
            last_resolution_status?: string;
        } & {
            [key: string]: unknown;
        };
        OktaEvaluationRequest: {
            mission_version_seen?: number;
            actor: {
                [key: string]: unknown;
            };
            action: {
                type?: string;
                name?: string;
                resource?: {
                    type: string;
                    id: string;
                };
                operation?: string;
            } & {
                [key: string]: unknown;
            };
        };
        ResolveOktaAuthorityContextRequest: {
            tenant_id?: string;
            mission_ref?: string;
            issuer?: string;
            client_id?: string;
            subject?: string;
            groups?: string[];
            scopes?: string[];
            claims?: {
                [key: string]: unknown;
            };
            context?: {
                [key: string]: unknown;
            };
            evaluation?: components["schemas"]["OktaEvaluationRequest"];
        };
        OktaAuthorityContextResponse: {
            accepted: boolean;
            status: string;
            binding_id?: string;
            tenant_id?: string;
            mission_ref?: string;
            issuer?: string;
            client_id?: string;
            subject?: string;
            groups?: string[];
            scopes?: string[];
            admin: boolean;
            reason_codes?: string[];
            human_reason?: string;
            context?: {
                [key: string]: unknown;
            };
            evaluation?: {
                [key: string]: unknown;
            };
            resolved_at?: string;
        } & {
            [key: string]: unknown;
        };
        CreateEntraAppRegistrationRequest: {
            tenant_id?: string;
            tenant_name?: string;
            /** @description Microsoft Entra issuer, for example https://login.microsoftonline.com/{tenant}/v2.0. */
            issuer: string;
            client_id: string;
            app_id?: string;
            app_name?: string;
            mission_ref: string;
            required_groups?: string[];
            admin_groups?: string[];
            allowed_subjects?: string[];
            group_claim?: string;
            subject_claim?: string;
            roles_claim?: string;
            /** @enum {string} */
            group_match_mode?: "any" | "all";
            metadata?: {
                [key: string]: string;
            };
        };
        EntraAppRegistration: {
            registration_id: string;
            tenant_id?: string;
            tenant_name?: string;
            issuer: string;
            discovery_url?: string;
            jwks_uri?: string;
            client_id: string;
            app_id?: string;
            app_name?: string;
            mission_ref: string;
            required_groups?: string[];
            admin_groups?: string[];
            allowed_subjects?: string[];
            group_claim?: string;
            subject_claim?: string;
            roles_claim?: string;
            group_match_mode?: string;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            last_resolved_at?: string;
            last_subject?: string;
            last_resolution_status?: string;
        } & {
            [key: string]: unknown;
        };
        EntraEvaluationRequest: {
            mission_version_seen?: number;
            actor: {
                [key: string]: unknown;
            };
            action: {
                type?: string;
                name?: string;
                resource?: {
                    type: string;
                    id: string;
                };
                operation?: string;
            } & {
                [key: string]: unknown;
            };
        };
        ResolveEntraAuthorityContextRequest: {
            tenant_id?: string;
            mission_ref?: string;
            issuer?: string;
            client_id?: string;
            subject?: string;
            groups?: string[];
            roles?: string[];
            claims?: {
                [key: string]: unknown;
            };
            context?: {
                [key: string]: unknown;
            };
            evaluation?: components["schemas"]["EntraEvaluationRequest"];
        };
        EntraAuthorityContextResponse: {
            accepted: boolean;
            status: string;
            registration_id?: string;
            tenant_id?: string;
            mission_ref?: string;
            issuer?: string;
            client_id?: string;
            subject?: string;
            groups?: string[];
            roles?: string[];
            admin: boolean;
            reason_codes?: string[];
            human_reason?: string;
            context?: {
                [key: string]: unknown;
            };
            evaluation?: {
                [key: string]: unknown;
            };
            resolved_at?: string;
        } & {
            [key: string]: unknown;
        };
        AdminSession: {
            principal: components["schemas"]["Principal"];
            capabilities: {
                [key: string]: boolean;
            };
            api_version: string;
        };
        OperationsSummary: {
            missions_total: number;
            missions_by_state: {
                [key: string]: number;
            };
            pending_proposals: number;
            pending_expansions: number;
            active_containments: number;
            active_agents: number;
            active_projections: number;
            recent_event_count: number;
            service_capabilities: {
                [key: string]: unknown;
            };
        };
        MissionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Mission"][];
        };
        ProposalPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["MissionProposal"][];
        };
        ExpansionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["ExpansionRequest"][];
        };
        AgentPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["AgentIdentity"][];
        };
        ToolContractPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["ToolContract"][];
        };
        ProjectionPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["Projection"][];
        };
        EventPage: components["schemas"]["Page"] & {
            items?: components["schemas"]["EventRecord"][];
        };
        Page: {
            items: unknown[];
            next_cursor?: string;
            total: number;
        };
    };
    responses: {
        /** @description Stable API error envelope. */
        Error: {
            headers: {
                "X-Request-ID"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
    };
    parameters: {
        AgentID: string;
        ExpansionID: string;
        LeaseID: string;
        MissionRef: string;
        ProjectionID: string;
        Tenant: string;
        Query: string;
        Status: string;
        State: string;
        Type: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: {
        GenericJSON: {
            content: {
                "application/json": components["schemas"]["GenericObject"];
            };
        };
    };
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service health. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMissionAuthorityDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission authority discovery document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAuthZENDiscovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description AuthZEN discovery document. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    evaluateAuthZEN: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description AuthZEN single evaluation decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    evaluateAuthZENBatch: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description AuthZEN batch evaluation decisions. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAdminSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated administrator context. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminSession"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getOperationsSummary: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current operator dashboard counters. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationsSummary"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMissions: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    evaluateMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Mission-scoped authorization decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createAuthorityNegotiation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Authority negotiation. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createExpansionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Expansion request. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpansionRequest"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resumeMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Mission resume decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    delegateMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Delegated child mission. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Revoked mission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    completeMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Completed mission. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    introspectMission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Mission"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMissionLineage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission lineage graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createProjection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Signed external projection. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createMissionLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                mission_ref: components["parameters"]["MissionRef"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Mission lease decision. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listMissionProposals: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission proposal page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProposalPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createMissionProposal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Created mission proposal. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMissionProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Mission proposal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MissionProposal"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    approveMissionProposal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                proposal_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Activated mission. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listExpansionRequests: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expansion request page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpansionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getExpansionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expansion_id: components["parameters"]["ExpansionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Expansion request. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExpansionRequest"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    approveExpansionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expansion_id: components["parameters"]["ExpansionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Expansion approval decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    denyExpansionRequest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expansion_id: components["parameters"]["ExpansionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Expansion denial decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    submitExpansionApproval: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                expansion_id: components["parameters"]["ExpansionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Recorded expansion approval. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listAgents: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent identity page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerAgent: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Registered agent identity. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentIdentity"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Revoked agent identity. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentIdentity"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAgentLineage: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: components["parameters"]["AgentID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent lineage graph. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listToolContracts: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool contract page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolContractPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    registerToolContract: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Registered tool contract. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolContract"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getToolContract: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tool_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tool contract. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToolContract"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    authorizeToolCall: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Tool-call authorization decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listProjections: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projection page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getProjectionStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projection_id: components["parameters"]["ProjectionID"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projection status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    revokeProjection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                projection_id: components["parameters"]["ProjectionID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Revoked projection status. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyProjection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Projection verification result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listGitHubRepositoryBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description GitHub repository bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        repositories: components["schemas"]["GitHubRepositoryBinding"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createGitHubRepositoryBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGitHubRepositoryBindingRequest"];
            };
        };
        responses: {
            /** @description GitHub repository binding. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubRepositoryBinding"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    ingestGitHubWebhook: {
        parameters: {
            query?: never;
            header: {
                "X-GitHub-Event": string;
                "X-GitHub-Delivery": string;
                "X-Hub-Signature-256": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Accepted GitHub webhook delivery. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubWebhookResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    planGitHubCheckRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GitHubCheckRunPlanRequest"];
            };
        };
        responses: {
            /** @description GitHub check-run payload that an integration worker can publish. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GitHubCheckRunPlanResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listOktaAppBindings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Okta application bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        app_bindings: components["schemas"]["OktaAppBinding"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOktaAppBinding: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOktaAppBindingRequest"];
            };
        };
        responses: {
            /** @description Okta application binding. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OktaAppBinding"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resolveOktaAuthorityContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveOktaAuthorityContextRequest"];
            };
        };
        responses: {
            /** @description Canonical mission authority context resolved from verified Okta claims. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OktaAuthorityContextResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEntraAppRegistrations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entra application registration bindings. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        app_registrations: components["schemas"]["EntraAppRegistration"][];
                    };
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createEntraAppRegistration: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEntraAppRegistrationRequest"];
            };
        };
        responses: {
            /** @description Entra application registration binding. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntraAppRegistration"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    resolveEntraAuthorityContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveEntraAuthorityContextRequest"];
            };
        };
        responses: {
            /** @description Canonical mission authority context resolved from verified Entra claims. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntraAuthorityContextResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listEvents: {
        parameters: {
            query?: {
                tenant_id?: components["parameters"]["Tenant"];
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                state?: components["parameters"]["State"];
                type?: components["parameters"]["Type"];
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit event page. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPage"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-sent audit event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listApprovalRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Approval rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createApprovalRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Approval rule. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    listContainmentRules: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containment rules. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createContainmentRule: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Containment rule. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getContainmentRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containment rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    liftContainmentRule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Lifted containment rule. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainmentRule"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getContainmentBlastRadius: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Containment blast radius. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAuthorityNegotiation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                negotiation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authority negotiation. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    verifyDecisionArtifact: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Decision artifact verification result. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    refreshMissionLease: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lease_id: components["parameters"]["LeaseID"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["GenericJSON"];
        responses: {
            /** @description Refreshed mission lease decision. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GenericObject"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
