import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { ArrowRight, Plus, ShieldAlert, X } from "lucide-react";
import { useState } from "react";
import { useApi } from "../../shared/auth/SessionProvider";
import { ErrorState, LoadingState } from "../../shared/components/AsyncState";
import { PageHeader } from "../../shared/components/PageHeader";
import { StatusBadge } from "../../shared/components/StatusBadge";
import { formatDate } from "../../shared/formatting";

export function ContainmentPage() {
  const api = useApi();
  const client = useQueryClient();
  const [creating, setCreating] = useState(false);
  const [form, setForm] = useState({ tenant_id: "demo", target_type: "mission", target_id: "", reason: "", expires_at: "" });
  const rules = useQuery({ queryKey: ["containment"], queryFn: () => api.listContainment() });
  const create = useMutation({ mutationFn: () => api.createContainment({ ...form, expires_at: form.expires_at ? new Date(form.expires_at).toISOString() : undefined } as any), onSuccess: async () => { setCreating(false); setForm({ tenant_id: "demo", target_type: "mission", target_id: "", reason: "", expires_at: "" }); await Promise.all([client.invalidateQueries({ queryKey: ["containment"] }), client.invalidateQueries({ queryKey: ["summary"] })]); } });
  return <><PageHeader eyebrow="Emergency authority" title="Containment" description="Fail-closed controls and their affected mission authority." actions={<button className="button button-danger" onClick={() => setCreating((value) => !value)}>{creating ? <X size={16} /> : <Plus size={16} />}{creating ? "Close" : "New containment"}</button>} />{creating ? <section className="create-band"><div className="create-band-heading"><ShieldAlert size={21} /><div><h2>Create containment rule</h2><p>The authenticated principal is recorded by the service.</p></div></div><div className="inline-form"><label className="field"><span>Tenant</span><input value={form.tenant_id} onChange={(event) => setForm({ ...form, tenant_id: event.target.value })} /></label><label className="field"><span>Target type</span><select value={form.target_type} onChange={(event) => setForm({ ...form, target_type: event.target.value })}><option value="mission">Mission</option><option value="agent">Agent</option><option value="principal">Principal</option><option value="tool">Tool</option><option value="resource">Resource</option><option value="tenant">Tenant</option></select></label><label className="field"><span>Target ID</span><input value={form.target_id} onChange={(event) => setForm({ ...form, target_id: event.target.value })} /></label><label className="field"><span>Expires at</span><input type="datetime-local" value={form.expires_at} onChange={(event) => setForm({ ...form, expires_at: event.target.value })} /></label><label className="field field-wide"><span>Reason</span><input value={form.reason} onChange={(event) => setForm({ ...form, reason: event.target.value })} /></label><button className="button button-danger" disabled={!form.target_id || !form.reason || create.isPending} onClick={() => create.mutate()}><ShieldAlert size={16} />{create.isPending ? "Creating..." : "Activate containment"}</button></div>{create.error ? <p className="form-error">{create.error.message}</p> : null}</section> : null}<section className="content-section">{rules.isLoading ? <LoadingState /> : rules.isError ? <ErrorState error={rules.error} /> : <div className="containment-list">{rules.data!.containment_rules.map((rule) => <Link key={rule.rule_id} to="/containment/$ruleId" params={{ ruleId: rule.rule_id }} className="containment-row"><div className={`containment-marker ${rule.status === "active" ? "marker-active" : ""}`}><ShieldAlert size={18} /></div><div className="containment-main"><strong>{rule.target_type}: {rule.target_id}</strong><span>{rule.reason || "No reason"}</span></div><div className="containment-meta"><StatusBadge value={rule.status} /><span>{rule.expires_at ? `Expires ${formatDate(rule.expires_at)}` : "No expiry"}</span></div><ArrowRight size={16} /></Link>)}{!rules.data!.containment_rules.length ? <div className="compact-empty">No containment rules recorded.</div> : null}</div>}</section></>;
}
