import { useQuery } from "@tanstack/react-query";
import { Activity, Search, XCircle } from "lucide-react";
import { useState } from "react";
import { useApi } from "../../shared/auth/SessionProvider";
import { ErrorState, LoadingState } from "../../shared/components/AsyncState";
import { JsonBlock } from "../../shared/components/JsonBlock";
import { PageHeader } from "../../shared/components/PageHeader";
import { formatDate, shortID, titleCase } from "../../shared/formatting";

export function AuditPage() {
  const api = useApi(); const [query, setQuery] = useState(""); const [type, setType] = useState(""); const [selected, setSelected] = useState<string | null>(null);
  const events = useQuery({ queryKey: ["events", query, type], queryFn: () => api.listEvents({ q: query, type, limit: 100 }) });
  const current = events.data?.items.find((item) => item.event_id === selected);
  const hasFilters = Boolean(query.trim() || type.trim());
  return <><PageHeader eyebrow="Immutable ledger" title="Audit events" description="Trace state changes through mission, causation, and correlation identifiers." /><div className="filter-bar"><label className="search-field"><Search size={16} /><span className="sr-only">Search events</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search event, mission, causation, or correlation" /></label><label className="search-field event-type-field"><Activity size={16} /><span className="sr-only">Filter event type</span><input value={type} onChange={(event) => setType(event.target.value)} placeholder="Exact event type" /></label><span className="result-count">{events.data?.total ?? 0} events</span></div><div className="audit-layout"><section className="content-section audit-list">{events.isLoading ? <LoadingState /> : events.isError ? <ErrorState error={events.error} /> : events.data!.items.length ? events.data!.items.map((event) => <button className={`audit-row ${selected === event.event_id ? "audit-row-selected" : ""}`} key={event.event_id} onClick={() => setSelected(event.event_id)}><div className="timeline-dot"><Activity size={13} /></div><div><strong>{titleCase(event.type)}</strong><span>{event.mission_ref ? shortID(event.mission_ref, 14) : "System event"}</span></div><time>{formatDate(event.occurred_at)}</time></button>) : <div className="empty-state audit-empty"><Activity size={24} /><strong>{hasFilters ? "No events match these filters" : "No audit events"}</strong><span>{hasFilters ? "Broaden the search or clear filters to return to the ledger." : "Authority events will appear here."}</span>{hasFilters ? <button className="button button-secondary" onClick={() => { setQuery(""); setType(""); setSelected(null); }}><XCircle size={15} />Clear filters</button> : null}</div>}</section><aside className="audit-detail">{current ? <><div className="section-heading"><div><span className="section-kicker">Event detail</span><h2>{titleCase(current.type)}</h2></div></div><dl className="definition-grid definition-grid-single"><div><dt>Event ID</dt><dd><code>{current.event_id}</code></dd></div><div><dt>Mission</dt><dd>{current.mission_ref || "System"}</dd></div><div><dt>Correlation</dt><dd>{current.correlation_id || "Not set"}</dd></div><div><dt>Causation</dt><dd>{current.causation_id || "Not set"}</dd></div></dl><JsonBlock value={{ actor: current.actor, payload: current.payload, version_before: current.version_before, version_after: current.version_after }} label="Event payload" /></> : <div className="empty-state"><Activity size={24} /><strong>Select an event</strong><span>Event evidence will appear here.</span></div>}</aside></div></>;
}
